steps:
  - name: bear
    plugin: 'DrushFetcher'
    params:
      yes: 'true'
      verbose: 'true'
      sql-sync: 'true'
      remote-environment: staging
      local-environment: probo
    config:
      settings_php.snippets: []
  - name: Force checkout git commit
    command: 'cd /var/www/bear/webroot ; git checkout -f $COMMIT_REF .'
  - name: Rewrite settings.php file
    command: 'drush fetcher-task ensure_settings_file bear --remote-environment=staging -y'
  - name: Fix permissions
    command: 'chown -R www-data:www-data /var/www/bear/public_files'
