steps:
  - name: Install drush-master for d8
    command: 'composer global require drush/drush:dev-master ; cd /usr/local/bin ; mv drush drush7 ; ln -s $HOME/.composer/vendor/bin/drush drush'
  - name: Make and install Bear
    plugin: Drupal
    makeFile: probo.make
    profileName: bear
    runInstall: true
  - name: Run behat tests
    command: 'cd /var/www/html/profiles/bear/tests ; composer install ; ./bin/behat --profile probo'
