steps:
  - name: bear
    plugin: 'DrushFetcher'
    params:
      yes: 'true'
      verbose: 'true'
      sql-sync: 'true'
      remote-environment: staging
      local-environment: probo
    config:
      settings_php.snippets: []
  - name: Force checkout git commit
    command: 'cd /var/www/bear ; git clone git@github.com:zivtech/bear.git ; cd bear ; git checkout -f $COMMIT_REF .'
  - name: Fix permissions
    command: 'chown -R www-data:www-data /var/www/bear/public_files'
